import client from 'prom-client';

// Create a custom registry
export const register = new client.Registry();

// Enable default Node.js runtime metrics (Heap, Event Loop, GC, CPU)
client.collectDefaultMetrics({
  register,
});


// --- HTTP Metrics ---
export const httpRequestDuration = new client.Histogram({
  name: 'http_request_duration_seconds',
  help: 'Duration of HTTP requests in seconds',
  labelNames: ['method', 'route', 'status_code'],
  buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],
  registers: [register],
});

export const httpRequestsTotal = new client.Counter({
  name: 'http_requests_total',
  help: 'Total number of HTTP requests',
  labelNames: ['method', 'route', 'status_code'],
  registers: [register],
});

// --- LLM (Ollama) Metrics ---
export const llmInferenceDuration = new client.Histogram({
  name: 'llm_inference_duration_seconds',
  help: 'Duration of Ollama LLM inference in seconds',
  labelNames: ['model', 'status'],
  buckets: [0.1, 0.5, 1, 2, 3, 5, 8, 12, 20, 30],
  registers: [register],
});

export const llmPromptEvalDuration = new client.Histogram({
  name: 'llm_prompt_eval_duration_seconds',
  help: 'Duration of LLM prompt evaluation in seconds',
  labelNames: ['model'],
  buckets: [0.05, 0.1, 0.25, 0.5, 1, 2, 5],
  registers: [register],
});

export const llmTokensGenerated = new client.Counter({
  name: 'llm_tokens_generated_total',
  help: 'Total output tokens generated by the LLM',
  labelNames: ['model'],
  registers: [register],
});

export const llmPromptTokens = new client.Counter({
  name: 'llm_prompt_tokens_total',
  help: 'Total input tokens evaluated by the LLM',
  labelNames: ['model'],
  registers: [register],
});

export const llmTokensPerSecond = new client.Histogram({
  name: 'llm_tokens_per_second',
  help: 'Token generation speed (tokens/sec) of the LLM',
  labelNames: ['model'],
  buckets: [5, 10, 15, 20, 25, 30, 40, 50, 75, 100],
  registers: [register],
});

export const llmRequestsTotal = new client.Counter({
  name: 'llm_requests_total',
  help: 'Total number of LLM inference requests',
  labelNames: ['model', 'status'],
  registers: [register],
});

export const llmParsingErrorsTotal = new client.Counter({
  name: 'llm_parsing_errors_total',
  help: 'Total number of LLM response parsing failures or heuristic fallbacks',
  labelNames: ['model', 'error_type'],
  registers: [register],
});

// --- AI Pipeline Metrics (Whisper, OCR) ---
export const aiPipelineDuration = new client.Histogram({
  name: 'ai_pipeline_duration_seconds',
  help: 'Duration of AI pipeline stages in seconds',
  labelNames: ['pipeline_type', 'status'],
  buckets: [0.1, 0.5, 1, 2, 3, 5, 10, 20],
  registers: [register],
});

// --- Kafka Metrics ---
export const kafkaMessagesPublished = new client.Counter({
  name: 'kafka_messages_published_total',
  help: 'Total Kafka messages published by producer',
  labelNames: ['topic', 'status'],
  registers: [register],
});

export const kafkaPublishDuration = new client.Histogram({
  name: 'kafka_publish_duration_seconds',
  help: 'Duration to publish Kafka message in seconds',
  labelNames: ['topic'],
  buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1],
  registers: [register],
});

export const kafkaMessagesConsumed = new client.Counter({
  name: 'kafka_messages_consumed_total',
  help: 'Total Kafka messages processed by consumers',
  labelNames: ['topic', 'consumer_group', 'status'],
  registers: [register],
});

export const kafkaConsumerDuration = new client.Histogram({
  name: 'kafka_consumer_processing_duration_seconds',
  help: 'Time taken to process a Kafka message in seconds',
  labelNames: ['topic', 'consumer_group', 'status'],
  buckets: [0.05, 0.1, 0.5, 1, 2, 5, 10, 20],
  registers: [register],
});

